<?php
/**
 * @var $form \Zend\Form\Form
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
$form = $this->get('loginForm');
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
?>

<h1><?= $this->translate('Sign In') ?></h1>

<?= $this->form()->openTag($form) ?>
    <?= $this->formElementErrors($form->get('identity')) ?>

    <?php if ($this->get('redirect')): ?>
        <input type="hidden" name="redirect" value="<?= $this->escapeHtml($this->get('redirect')) ?>">
    <?php endif ?>

    <?= $this->formCollection($form) ?>

<?= $this->form()->closeTag() ?>

<?php if ($this->get('enableRegistration')) : ?>
    <?= $this->translate('Not registered?') ?>
    <a href="<?= $this->url('zfcuser/register') . ($this->get('redirect') ? '?redirect='. $this->get('redirect') : '') ?>">
        <?= $this->translate('Sign up!'); ?>
    </a>
<?php endif; ?>
