<?php
/**
 * @var $form \Zend\Form\Form
 * @var $this \Zend\View\Renderer\PhpRenderer
 */
if (!$this->get('enableRegistration')) {
    echo $this->translate('Registration is disabled');
    return;
}

$form = $this->get('registerForm');
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/register'));
$form->setAttribute('method', 'post');
?>

<h1><?= $this->translate('Register') ?></h1>

<?= $this->form()->openTag($form) ?>
    <?php if ($this->get('redirect')): ?>
        <input type="hidden" name="redirect" value="<?= $this->escapeHtml($this->get('redirect')) ?>">
    <?php endif ?>
    <?= $this->formCollection($form) ?>
<?php echo $this->form()->closeTag() ?>
